FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD /tmp/helloworld.jar helloworld.jar
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /helloworld.jar" ]
